# Generated by Django 2.0.7 on 2018-07-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placio_month', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='csvimport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y-%m-%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CSVsave',
        ),
    ]
