# Generated by Django 2.1 on 2018-08-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placio_month', '0002_auto_20180723_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='graph_axis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.CharField(max_length=200)),
                ('hue', models.CharField(max_length=200)),
            ],
        ),
    ]
