# Generated by Django 2.1 on 2018-08-30 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placio_month', '0003_graph_axis'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='graph_axis',
            name='graphName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='placio_month.GraphType'),
        ),
    ]
