# Generated by Django 2.1 on 2018-08-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placio_month', '0004_auto_20180830_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph_axis',
            name='graphName',
            field=models.CharField(max_length=200),
        ),
    ]
